**План действий**
1. Применить маску к фотографиям \(убрать море, чтобы сеть быстрее обучалась\)
2. Использовать полноразмерные изображения \(выше точность\(?\)
3. SIFT / ROOTSIFT для извлечения точек
4. FAISS для сопоставления точек
5. Применить метод Keypoint Matching

![image](researchings/img.png 'Title')

Импорт библиотек

In [1]:
import tensorflow as tf
from tensorflow import keras
from pathlib import Path
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
import cv2
print('Библиотеки успешно загружены')

Библиотеки успешно загружены


Применить маску к изображениям

Переместить маски в зеркальную папку

In [80]:
dataset_directory = Path('Whale ReId 2_mm')
mask_directory = 'Whale ReId 2_mm masked'

for file in dataset_directory.glob('**/*.png'):
    Path(mask_directory, *file.parts[1:-1]).mkdir(parents=True, exist_ok=True)
    file.rename(Path(mask_directory, *file.parts[1:]))


Загрузить дата-сет

In [5]:
dataset = keras.utils.image_dataset_from_directory('Whale ReId 2_mm', labels='inferred', shuffle='False', batch_size=64, interpolation='mitchellcubic',color_mode='rgb')
masks = keras.utils.image_dataset_from_directory('Whale ReId 2_mm masked', labels='inferred', shuffle='False', batch_size=64, color_mode='grayscale')

Found 33644 files belonging to 102 classes.
Found 33644 files belonging to 102 classes.


Перемножить

In [6]:
class_names = dataset.class_names

In [9]:
class DataGenerator(Sequence)

tf.Tensor(
[[[[ 61.43734   88.43734   73.43734 ]
   [ 68.43593   95.43592   80.43594 ]
   [ 65.26733   92.26732   77.267334]
   ...
   [ 73.95193   97.9625    81.96251 ]
   [ 75.        99.        83.00001 ]
   [ 71.61074   95.61074   79.61074 ]]

  [[ 60.64655   87.64655   72.64655 ]
   [ 65.10684   92.10683   77.106834]
   [ 66.98938   93.98937   78.98937 ]
   ...
   [ 73.9812    97.99177   81.99178 ]
   [ 75.        98.999985  82.999985]
   [ 72.060234  96.060234  80.060234]]

  [[ 62.81904   89.819046  74.819046]
   [ 64.98193   91.98192   76.98194 ]
   [ 66.246216  93.246216  78.24622 ]
   ...
   [ 73.99127   98.00184   82.00184 ]
   [ 74.99999   98.99999   82.99999 ]
   [ 72.56958   96.56957   80.56958 ]]

  ...

  [[ 65.0456    98.0456    81.0456  ]
   [ 66.86767   97.86765   81.86765 ]
   [ 72.01385  100.02958   85.02786 ]
   ...
   [ 50.019623  81.44341   63.242092]
   [ 52.83985   83.83984   65.83985 ]
   [ 55.679993  84.67998   66.67999 ]]

  [[ 62.062183  95.06218   78.0621

Отобразить

In [130]:
plt.figure(figsize=(16, 16))
for images, labels in dataset.take(1):
    for i in range(4):
        ax = plt.subplot(2, 2, i + 1)
        plt.title(class_names[labels[i]])
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.axis("off")


AttributeError: 'ZipDataset' object has no attribute 'class_names'

<Figure size 1600x1600 with 0 Axes>

Модель (?)